### PR TITLE
Add playSound function

### PR DESCRIPTION
**Pull request by jcheng5**
Just a simple function to play a sound from a Shiny app.

(Licensing note: the MP3 file I embedded for the example is public domain, from here: http://soundbible.com/1598-Electronic-Chime.html)

### CODE REVIEW

**Comment by daattali** [comment]
Thanks Joe, a few small comments

- Is it necessary/good practice to both namespace a function AND `#'
@import` it? I usually just namespace without explicitly importing, but I'd
like to know if your way is considered better
- Does this work in the RStudio Viewer panel? I assume it requires a real
browser. I see there's a comment saying it's browser dependent, but might
be worth to mention that it certainly does not work inside RStudio (because
a lot of people who develop shiny are mostly closed off inside RStudio and
don't realize there are differences between that and a browser)
- I think using the "file" arg would be more common than using the "src"
arg because I'd imagine people want to use local files instead of third
party URLs. If you agree, could you swap their positions in the argument
list?
- Could you capitalize "mime" in the documentation, that's just me being OCD

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by daattali** [comment]
Also, what do you think of adding "onended = 'this.remove()'" so that the DOM isn't infested with lots of expired audio tags?

**Comment by jcheng5** [comment]
Dang it. It worked on RStudio for Mac, I forgot to check on Windows. That really sucks. Maybe let's wait until RStudio for Windows supports it then.

**Comment by daattali** [comment]
I just tried in RStudio on Windows and it indeed does not work. I didn't
know the Mac RStudio had more features (or maybe just the built in browser
does?). Sure, can wait.

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by daattali** [comment]
Update: just checked, looks like sounds still not supported on Windows

**Comment by daattali** [comment]
Coming back to this half a decade later because I need this functionality. 

It does work now in RStudio Windows and also on mobile. Will need to update the documentation, see if there are any new audio file formats, and add `onended = 'this.remove()'`

**Comment by ch0c0l8ra1n** [comment]
@daattali Web Audio API objects are more suitable than audio tags for shinyjs. Plus it doesn't need to be removed from the DOM. I can have a PR sent that borrows most of @jcheng5's code but uses Web Audio API instead.

**Comment by daattali** [comment]
@ch0c0l8ra1n Do you know if there are other shiny packages that are focused strictly on audio and have this functionality?

**Comment by ch0c0l8ra1n** [comment]
@daattali I'm not aware of other shiny packages using the Web Audio API objects, or focused on audio in general. However, this is the standard way of playing audio for interactions. You'd use an audio tag if you were playing a song or something of the sort.

**Comment by daattali** [comment]
I was asking becasue this doesn't *quite* fit into the functionality of this package, but if there is no other dedicated audio package, I could see an argument for adding it here

**Comment by ch0c0l8ra1n** [comment]
There don't seem to be any popular shiny packages that have this functionality. There's a shiny wrapper for howler that might have this functionality but it also does **a lot** more.

**Comment by daattali** [comment]
To me it does look like {howler} might be a perfect place for such a function, but I'll ask the author, we'll see what he thinks, I trust his judgment.

@ashbaldry the `playSound` function that was proposed by Joe is a server-only function that can play an audio file from local or remote URL. Does such a function exist in your package, and if not do you think this function makes sense there?

**Comment by ashbaldry** [comment]
There isn't currently one in {howler}, but its certainly feasible to include something like `playSound` in the package to avoid needing the widget to run. The easiest way to currently do something similar to this in the current version looks like this:

```r
library(shiny)
library(howler)

ui <- fluidPage(
  howler(tracks = NULL, elementId = "sound"),
  actionButton("play", "Play sound")
)

server <- function(input, output, session) {
  observeEvent(input$play, {
    addTrack("sound", <file_to_add>, play_track = TRUE)
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by ashbaldry** [comment]
The `playSound` function is now available in the `main` branch of {howler}

```r
library(shiny)
library(howler)

audio_files_dir <- system.file("examples/_audio", package = "howler")
addResourcePath("sample_audio", audio_files_dir)

ui <- fluidPage(
  actionButton("play", "Play Sound")
)

server <- function(input, output) {
  observeEvent(input$play, {
    playSound("sample_audio/running_out.mp3")
  })
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
Fantastic. I think that's the ebat place for this function in 2024. @ch0c0l8ra1n you can use howler now for this

**Comment by ch0c0l8ra1n** [comment]
@daattali Thanks but I didn't need the function particularly. I'm just helping around!

**Pull request closed without merging**
