### PR TITLE
Textarea can now be disabled too.

### PR DESCRIPTION
**Pull request by deeflorian**

### CODE REVIEW

**Comment by daattali** [comment]
Thank you for taking the time to understand the code and add it, rather than just opening an issue. Much appreciated

**Comment by daattali** [comment]
I hope my code was simple/documented enough to make your job easy :)

**Comment by deeflorian** [comment]
The issue description would have had more characters in it than the actual fix. Took about 10 minutes to add including testing and the pull request, so I'd say the repo is in a pretty neat condition :)

**Comment by daattali** [comment]
Really glad to hear!

**Pull request merged**
