### PR TITLE
In runCode, capture printed expression output for rendering (if desired).

### PR DESCRIPTION
**Pull request by gwarnes-mdsol**
I often want to see output from the R commands evaluated in `runCode`.    With this change, the following code (captured in the roxygen documentation) now works properly:
```
  shinyApp(
    ui = fluidPage(
      useShinyjs(),  # Set up shinyjs
      runcodeUI(code = "shinyjs::alert('Hello!')"),
      shiny::tags$br(),
      shiny::tags$label("Output:"),
      textOutput("runcode_output", container=pre)
    ),
    server = function(input, output) {
      runcodeServer()
    }
  )
```

For example:
image

### CODE REVIEW

**Comment by gwarnes-mdsol** [comment]
> Function documentation needs to mention this feature (just putting it in the examples is not enough, it's not clear)

Done.

> The output render function should not be created inside an observer, that leads to potentially strange incorrect behaviour

Hmm. If `renderText` is not inside the observer, the results need to be stashed somewhere so that the user code can get to them.  How do you recommend this be handled?   Have the user pass-in a `reactiveValues` object?

> Couldn't this be made into a parameter - something like showOutput=TRUE/FALSE?

Done.

> What benefit does changing the eval() to withAutoprint() serve?

`withAutoprint` captures the printed output as if the commands had been entered into the console and returns this as a character vector.  `eval` executes the code, but doesn't capture output, and only returns the value of the last evaluated expression.

> The parent environment is discarded - does this work when using variables defined in the parent env?

Fixed.

I also added an (optional) parameter `preprocess` to allow the user to supply a function that can modify the entered R code.  This allows me to handle my case (as illustrated in the example) without creating special-case code in side of `runcode` or imposing my desired behavior on anyone else.

**Comment by daattali** [comment]
I still don't see the reason of using `source()` instead of `eval()`. You added a capture.output that takes care of capturing the output, which will work on both functions. This feels like more of an evaluating job rather than source-ing. Are there usecases you were using where eval didn't make sense?

**Comment by gwarnes-mdsol** [comment]
The primary purpose of using `source()` instead of `eval()` is to avoid the need to wrap everything in `print()` to see the results (and having to explain why it would be necessary to do so).

For example, a little while ago I used the `runCode(..., type = "textarea")` to look at the values of several variables in a `reactiveValues` object.  Input:
```
table(data$dataset$clin_data$processed$XXXX, useNA="a")
stem(data$dataset$clin_data$processed$YYYY_Derived)
```
yielding:
```
> table(data$dataset$clin_data$processed$XXXX, useNA = "a")

FALSE  TRUE  <NA> 
  123    79     0 
> stem(data$dataset$clin_data$processed$YYYY_Derived)

  The decimal point is 1 digit(s) to the right of the |

  2 | 4
  2 | 555556789
  3 | 00122223334444
  3 | 55555555555666677777899999999
  4 | 01244444
  4 | 5555555566678888888999999
  5 | 0000001111122234444444
  5 | 55555555556666667788888899999
  6 | 00012222223333334
  6 | 5555555666778889
  7 | 0000234
  7 | 55666678
  8 | 11122344
  8 | 57
```
with eval, it would be necessary to call `print()` as well as a couple of `cat("\n")` to separate things.

**Comment by daattali** [comment]
Ah, got it. I suppose the intention of this runcode function was more to allow you to run a piece of code purely for evaluation/side effect, not as a tool to run a collection of expressions and see their respective outputs, so this wasn't in my mind. But I understand now :+1:

**Comment by gwarnes-mdsol** [comment]
@daattali Any status on this?

**Comment by daattali** [comment]
Hi Gregory,
Sorry for not replying (much) sooner, I've been thinking about this and I think I prefer not to add it. The purpose of runCode is to be a simple lightweight way to **run** code , just to get something to happen. It there was an elegant simple way to also extract the output out of it that would be fine, but these changes are too heavy and result in code that isn't super clean. They require the user to do more than just call the function (having to add a textOutput), and it uses an antipattern that should not be used in shiny apps (using a render inside an observer). Overall I think it would make more sense for a user who wants to retrieve the output of a command to write the code to do that

**Comment by daattali** [comment]
@gwarnes-mdsol I kept this PR open so that I might warm up to the idea, but I still have not :P I'm going to close this one but I do appreciate your effort

**Pull request closed without merging**
