### PR TITLE
adding shinyAce?

### PR DESCRIPTION
**Pull request by shabbychef**
Addressing issue #93 , adds shinyAce editor support. I have not tested this yet, though. (ducks)

### CODE REVIEW

**Comment by daattali** [comment]
I've never usd shinyace before, what do the vimkeybindings and hotkeys params that you added do? I was thinking since shinyace has so many more optional params, maybe there could be a `...` param added to runcodeUI() and those ... would be passed along to shinyace

**Comment by shabbychef** [comment]
hmmm, the `vimkeybindings` make the editor act like vim. That's somewhat controversial, of course. The `hotkeys` allow the input to 'fire' when one of the keys is pressed, say F9, which I find more convenient than clicking a button (and mirrors my use of Conque in vim, noted at http://www.gilgamath.com/vim-ide.html). I am not sure if `...` is the right way to set up the plumbing here, I leave that to you.

**Comment by daattali** [comment]
I see. I'll accept this PR now so that you can start using it, but I'll leave the issue open because I'm going to want to come back to it later

**Comment by shabbychef** [comment]
Another sensible, though annoying alternative, would be to bring all the options of `aceEditor` into the API of `runcodeUI` (see https://github.com/trestletech/shinyAce/blob/master/R/ace-editor.R#L61-L67) by name, rather than relying on the implicit `...`.

**Pull request merged**
